packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@preact/preset-vite@2.10.6'
  - proto-tailwindcss-clrs@0.0.519
