packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  'esbuild': true
  'proto-tailwindcss-clrs': true

minimumReleaseAgeExclude:
  - '@preact/signals@2.10.0'
  - magic-string@1.1.0
  - proto-tailwindcss-clrs@0.0.524
